config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'weather' => 'weather#index', as: 'weather'
  get 'weather_results', to: 'weather#results', as: 'weather_results'

  # Defines the root path route ("/")
  # root "posts#index"
  root "weather#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location_weather.rb
# frozen_string_literal: true

# LocationWeather is a client for the chosed external weather API
# (currently Tomorrow.io) and abastracts most of the request interaction details
# with that api from the rest of the application.
#
# At present we present response JSON directly, so that part of the abstraction leaks
# to the rest of the application.
class LocationWeather
  WeatherApiError = Class.new(StandardError)
  RateLimitError = Class.new(StandardError)

  CONDITIONS_ENDPOINT_URL = 'https://api.tomorrow.io/v4/weather/realtime'

  INVALID_PARAMETERS_CODE = 400_001
  BAD_REQUEST_STATUS = 400
  RATE_LIMITED_STATUS = 429
  SUCCESS_STATUS = 200

  # Weather codes from the Tommorrow API
  WEATHER_CODES = {
    1000 => 'Clear',
    1100 => 'Mostly Clear',
    1101 => 'Partly Cloudy',
    1102 => 'Mostly Cloudy',
    1001 => 'Cloudy',
    2100 => 'Light Fog',
    2101 => 'Fog',
    4000 => 'Drizzle',
    4200 => 'Light Rain',
    4001 => 'Rain',
    4201 => 'Heavy Rain',
    5001 => 'Heavy Snow',
    6000 => 'Freezing Drizzle',
    6200 => 'Light Freezing Drizzle',
    6001 => 'Freezing Rain',
    6201 => 'Heavy Freezing Rain',
    7102 => 'Light Ice Pellets',
    7000 => 'Ice Pellets',
    7101 => 'Heavy Ice Pellets',
    8000 => 'Thunderstorm'
  }.freeze

  attr_reader :zip_code, :current, :current_fetched, :units

  def initialize(zip_code)
    @zip_code = zip_code
    @current_fetched = false
    @units = 'imperial'
    @current = {}
    @forecast = {}
    @found = false
    @error = false
  end

  def found?
    !!@found
  end

  def error?
    !!@error
  end

  def fetch_current
    @current = query_current
  end

  private

  def api_key
    Rails.env.test? ? 'testapikey' : ENV['TOMORROW_API_KEY']
  end

  def query_current
    Rails.logger.info("Getting current weather for #{@zip_code}")
    current = request_current_conditions
    return nil unless current

    check_response(current)

    current.body
  end

  def request_current_conditions
    Rails.cache.fetch(['weather', 'current', @zip_code].join('/'), expires_in: 30.minutes) do
      Rails.logger.debug('Calling external API')
      check_weather
    end
  end

  # Determine what happened so that clients of this class have feedback
  def check_response(response)
    response_body = response.body
    if response.status == SUCCESS_STATUS
      @found = true
    else
      Rails.logger.error(response_body['type'])
      Rails.logger.error(response_body['message'])
      @error = true
    end
    Rails.logger.debug(response)
  end

  # Call the weather api and return the response
  def check_weather
    @current_fetched = true
    wx_params = { 'location' => "#{@zip_code} US", 'units' => @units, 'apikey' => api_key }

    conn = Faraday.new(CONDITIONS_ENDPOINT_URL) do |f|
      f.request :json
      f.response :json
    end
    api_response = conn.get('', wx_params, { 'Accept' => 'application/json' })
    check_api_response(api_response)

    api_response
  end

  # Raise an error if the api response indicates an error that prevents displaying valid
  # results
  def check_api_response(api_response)
    # Ideally, we only want to cache responses that shouldn't be retried immediately.
    # Bad requests that result from locations not found, for example, could be cached
    # so that we don't try them again anytime soon. Other errors, such as rate limits
    # are temporary.

    if api_response.status == BAD_REQUEST_STATUS && api_response.body['code'] != INVALID_PARAMETERS_CODE
      raise WeatherApiError
    end
    raise RateLimitError if api_response.status == RATE_LIMITED_STATUS
    raise WeatherApiError if error_status?(api_response.status)
  end

  def error_status?(status_code)
    status_code.in?([401, 403, 404, 500])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

# Primary Rails controller for Querying of weather reports
class WeatherController < ApplicationController
  WEATHER_FIELDS = [
    ['temperature', 'Temperature', '°F'],
    ['temperatureApparent', 'Feels Like', '°F'],
    ['dewPoint', 'Dew Point', '°F'],
    ['humidity', 'Humidity', '%'],
    ['windSpeed', 'Wind Speed', 'mph'],
    ['windDirection', 'Wind Direction', 'degrees'],
    ['windGust', 'Window Gust', 'mph'],
    ['visibility', 'Visibility', 'mi'],
    ['cloudCover', 'Cloud Cover', 'mi']
  ].freeze

  rescue_from RuntimeError, with: :error_result

  def index; end

  def results
    @weather = fetch_weather if params[:zip_code].present?

    if @weather&.found?
      set_weather_fields
      render partial: 'results'
    else
      render partial: 'not_found'
    end
  rescue LocationWeather::RateLimitError
    render partial: 'too_many_requests'
  rescue LocationWeather::WeatherApiError
    render partial: 'error_results'
  end

  private

  # Handling rendering of an error response
  def error_result
    render partial: 'error_results'
  end

  # Set the field data for display
  def set_weather_fields
    @weather_fields = WEATHER_FIELDS
  end

  # Retrieve weather data from our data sources and set
  def fetch_weather
    Rails.logger.info("weather_request:#{params[:zip_code]}")

    weather = LocationWeather.new(params[:zip_code].strip)
    weather.fetch_current
    weather
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper

  def display_for_weather_code(weather_code)
    LocationWeather::WEATHER_CODES[weather_code]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_error_results.html.erb
<turbo-frame id='weather_results'>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    An error occurred and results can not be displayed. Please try again or contact an administrator.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</turbo-frame>

app/views/weather/_not_found.html.erb
<turbo-frame id='weather_results'>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Oh no!</strong> The zip-code '<%= @weather&.zip_code %>' was not found.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</turbo-frame>

app/views/weather/_results.html.erb
<turbo-frame id='weather_results'>
  <h1>Weather at <%= @weather.zip_code %></h1>
  <% unless @weather.current_fetched %>
    <span class="badge rounded-pill text-bg-info">cached</span>
  <% end %>
  <%= cache(['weather_results', @weather.zip_code, @weather.current.dig('data', 'time')]) do %>
    <div class="card">
      <div class="card-body">
        <table class="table table-sm">
          <tbody>
            <tr>
              <th>As of:</th>
              <td>
                <%= DateTime.parse(@weather.current.dig('data', 'time')).to_formatted_s(:long) %> UTC
              </td>
            </tr>
            <tr>
              <th>Location:</th>
              <td>
                <%= @weather.current.dig('location', 'name') %>
                <%= @weather.current.dig('location', 'lat') -%> <%= @weather.current.dig('location', 'lon') %>
              </td>
            </tr>
            <tr>
              <th>Conditions</th>
              <td><%= display_for_weather_code(@weather.current.dig('data', 'values', 'weatherCode')) %></td>
            </tr>
            <% @weather_fields.each do |field, title, unit| %>
              <tr>
                <th><%= title %></th>
                <td><%= [@weather.current.dig('data', 'values', field), unit].join('') %> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</turbo-frame>

app/views/weather/_too_many_requests.html.erb
<turbo-frame id='weather_results'>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    Results are not available at this time due to too many requests. Please try again later.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</turbo-frame>

app/views/weather/index.html.erb
<div class="container-md">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col text-center">
      <h1>Weather for Location</h1>
      <%= form_tag weather_results_path, method: :get, class: 'form weather-form', data: { 'turbo-frame' => 'weather_results' } do %>
        <div class="input-group mb-3">
          <span class="input-group-text">Zip Code</span>
          <%= text_field_tag 'zip_code', nil, type: :number, minlength: 1, required: true, step: 'any', placeholder: 'valid zip-code', class: 'form-control' %>
          <%= submit_tag 'Check', class: 'btn btn-sm btn-outline-secondary' %>
        </div>
      <% end %>
      <!-- Provide a place to put the last fetched results -->
      <turbo-frame id='weather_results'>
      </turbo-frame>
    </div>
    <div class="col"></div>
  </div>
</div>